on:
  push:

permissions:
  contents: read
  deployments: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      # - uses: docker://gittools/gitversion
      #   id: version
      #   with:
      #     args: >-
      #       .
      #       /showvariable FullSemVer
      # - run: echo "VERSION=${{steps.version.outputs.stdout}}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - uses: Illbjorn/setup-task@0.1.0
      - run: pip install reno git-cliff
      - uses: pandoc/actions/setup@v1
      - run: task build PUSH=$PUSH_FLAG
        env:
          PUSH_FLAG: ${{ github.ref_name == 'main' && 'true' || 'false' }}
      - uses: actions/upload-artifact@v4
        with:
          path: .vitepress/dist
          name: dist
          retention-days: 7
      # - uses: actions/cache@v4
      #   with:
      #     path: .vitepress/dist
      #     key: nc-build

  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.pages-deployment-alias-url }}
    needs: [build]
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dist
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy . --project-name=neoncode --branch ${{ github.ref_name }}
